version: '3'
services:
  django:
    image: 10.129.4.176:5000/stackweb:web_django
    build: ./django
    volumes:
      - /storage/nfs/website/volumes/static:/app/G7/G7App/static
    networks:
     - back
    hostname: django
    deploy:
      mode: global
    ports:
      - "8000:8000"
  
  nginx:
    image: 10.129.4.176:5000/stackweb:web_nginx
    build: ./nginx
    volumes:
      - /storage/nfs/website/volumes/static:/usr/share/nginx/html/static
    networks:
      - back
    hostname: nginx
    depends_on:
      - "django"
    deploy:
      mode: global
    ports:
      - "8080:8080"
networks:
  back:
