version: '3'
services:
  django:
    image: 10.129.4.176:5000/stackweb:web_django
    build: ./django
    volumes:
      - /storage/nfs/website/volumes/static:/app/G7/G7App/static
    networks:
     - back
    hostname: django
    deploy:
      mode: global
    expose:
      - 8000
    labels:
      - traefik.enable=true
      - traefik.http.routers.django.rule=Host(`10.129.4.176`) && not PathPrefix(`/static`)
      - traefik.http.middlewares.redirect-regex.redirectregex.regex=^/$
      - traefik.http.middlewares.redirect-regex.redirectregex.replacement=/G7App/index/
      - traefik.http.middlewares.redirect-regex.redirectregex.permanent=true
      - traefik.http.routers.django.middlewares=redirect-regex
  
  nginx:
    image: 10.129.4.176:5000/stackweb:web_nginx
    build: ./nginx
    volumes:
      - /storage/nfs/website/volumes/static:/usr/share/nginx/html/static
    networks:
      - back
    hostname: nginx
    depends_on:
      - "django"
    deploy:
      mode: global
    expose:
      - 8080
    labels:
      - traefik.enable=true
      - traefik.http.routers.django.rule=Host(`10.129.4.176`) && PathPrefix(`/static`)
networks:
  back:
