version: '3'
services:
  django:
    image: 10.129.4.176:5000/stackweb:web_django
    build: ./django
    volumes:
      - /storage/nfs/website/volumes/static:/app/G7/G7App/static
    networks:
     - back
    hostname: django
    deploy:
      mode: global
  
  nginx:
    image: 10.129.4.176:5000/stackweb:web_nginx
    build: ./nginx
    volumes:
      - /storage/nfs/website/volumes/static:/usr/share/nginx/html/static
    networks:
      - back
    hostname: nginx
    depends_on:
      - "django"
    deploy:
      mode: global

  proxy:
    image: 10.129.4.176:5000/stackweb:web_proxy
    build: ./HAProxy
    networks:
     - back
    ports:
     - "80:80"
    sysctls:
     - net.ipv4.ip_unprivileged_port_start=0
    depends_on:
     - "django"
     - "nginx"
    deploy:
      mode: global
  
networks:
  back:

volumes:
  static:

