version: '3'
services:
  django:
    image: 10.129.4.176:5000/stackweb:web_django
    build: ./django
    volumes:
      - /storage/nfs/website/volumes:/app/G7/G7App/static
    restart: unless-stopped
    networks:
     - back
    hostname: django
    deploy:
      mode: global
  
  nginx:
    image: 10.129.4.176:5000/stackweb:web_nginx
    build: ./nginx
    volumes:
      - /storage/nfs/website/volumes:/usr/share/nginx/html/static
    restart: unless-stopped
    networks:
      - back
    hostname: nginx
    depends_on:
      - "django"
    deploy:
      mode: global
  
networks:
  back:

volumes:
  static:

