version: '3'
services:
  django:
    image: 10.129.4.176:5000/stackweb:web_django
    build: ./django
    volumes:
      - static:/app/G7/G7App/static
    restart: unless-stopped
    networks:
     - back_django
    hostname: django
    deploy:
      mode: global
  


networks:
  back_nginx:
  back_django:

volumes:
  static:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /storage/nfs/website/volumes
